language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"

# install dependencies, e.g. pip install -r requirements.txt
install:
  - pip install coverage coveralls

#before_script:
#  - mkdir data

# run tests, e.g. python setup.py test
script:
  - coverage run --source="gravur" setup.py test

# TODO run coverage
# after_success:
#   - coveralls

# TODO post to slack
# notifications:
#   slack: F483:TODO_Token
#   email: false
