<IdentityPreview>:
    orientation: 'vertical'
    size_hint_y: None
    height: 65
    spacing: 1

    BoxLayout:
        spacing: 1
        size_hint_y: None
        height: 32

        LabelBox:
            text: root.alias

        LabelBox:
            text: root.timestamp
            size_hint_x: None
            width: 160

    LabelBox:
        text: root.address
        size_hint_y: None
        height: 32
