<BroadcastMessage>:
    BoxLayout:
        spacing: 1
        orientation: 'vertical'

        TextInput:
            id: message_input
            multiline: True
            hint_text: 'Message to be broadcast on the bitcoin blockchain.'

        LabelBox:
            text: 'TODO display fee here'

        StoreButton:
            storebutton_text: 'Broadcast Message'
            on_press: root.broadcast_message(message_input.text)
