<RetrieveFromTx>:
    BoxLayout:
        spacing: 1
        orientation: 'vertical'

        TextInput:
            id: txid_input
            multiline: False
            hint_text: 'transaction id'
            size_hint_y: None
            height: 32

        StoreButton:
            storebutton_text: 'Retrieve Message'
            on_press:
                screen = root.manager.get_screen('view_message')
                screen.display(txid_input.text)

        EigengrauBox:

